[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.4"

# Use Netlify's Next.js plugin for proper deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable secrets scanning for Firebase public keys
[build.processing.secrets]
  enabled = false

# Function settings for API routes
[functions]
  external_node_modules = ["firebase", "@google/generative-ai", "resend"]

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
